# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khrOELey7A51CpbgzNh9QDY4-KjsUj0-
"""

print("Hello from Sridhar!")